### PR TITLE
fix: ensure activity name is used when activity label is not defined

### LINKED ISSUE #150: screen_name is not set on $screen events - Using compose
### Version

3.4.2

### Steps to Reproduce

1. Initialise posthog in the application onCreate:
```
val config = PostHogAndroidConfig(
    apiKey = BuildConfig.ANDROID_KEY_POSTHOG,
    host = "https://eu.i.posthog.com",
    captureScreenViews = true,
    captureApplicationLifecycleEvents = true,
).apply {
    sessionReplay = false
    debug = BuildConfig.DEBUG
}
PostHogAndroid.setup(this, config)
```
3. Start an Activity (AppCompatActivity) with startActivity(Intent)
4. Start more activities

### Expected Result

$screen events logged for each activity with `screen_name` being the `Activity::class.java.name` or something related to the activity opened

### Actual Result

$screen events logged for each activity with `screen_name` being the value from `rootProject.name = ...` in the root `settings.gradle.kts` file

I'm using multiple activities all with compose inside them.

Please let me know if more info is needed to reproduce

### PR DESCRIPTION
**Pull request by thisames**
## :bulb: Motivation and Context

The loadLabel method was loading the application label when an activity label was not defined. This change ensures that when an activity label is not defined, it defaults to the activity name instead of the application label. This improves the accuracy of screen name logging.

fix #150 

## :green_heart: How did you test it?

- Unit tests were updated and run to verify the behavior of the new activityLabelOrName method.
- Additional test scenarios were added to ensure that the correct labels are returned when activity and application labels are the same or empty.
- Verified that existing tests pass without any issues.

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [ ] I updated the docs if needed.
- [x] No breaking change or entry added to the changelog.

### CODE REVIEW

File: posthog-android/src/main/java/com/posthog/android/internal/PostHogActivityLifecycleCallbackIntegration.kt [hunk 1]
```diff
@@ -41,14 +41,16 @@ internal class PostHogActivityLifecycleCallbackIntegration(
         }
     }
 
-    override fun onActivityStarted(activity: Activity) {
-        if (config.captureScreenViews) {
-            val activityLabel = activity.activityLabel(config)
-            if (!activityLabel.isNullOrEmpty()) {
-                PostHog.screen(activityLabel)
+        override fun onActivityStarted(activity: Activity) {
```
Comment (marandaneto) [inline posthog-android/src/main/java/com/posthog/android/internal/PostHogActivityLifecycleCallbackIntegration.kt:44]: identation is off here I think

**Review by marandaneto — APPROVED** [review]
Thanks @thisames

**Comment by marandaneto** [comment]
it does not fix https://github.com/PostHog/posthog-android/issues/150 but addresses another issue.

**Comment by thisames** [comment]
> @thisames would add a new item to the changelog file https://github.com/PostHog/posthog-android/blob/main/CHANGELOG.md ?

for sure =)

**Review by marandaneto — APPROVED** [review]

**Comment by marandaneto** [comment]
@thisames type `make format` and commit to fix the lint issues
